export const FETCH_APPOINTMENTS = "FETCH_APPOINTMENTS";
export const FETCH_APPOINTMENTS_SUCCESS = "FETCH_APPOINTMENTS_SUCCESS";
export const FETCH_APPOINTMENTS_FAILURE = "FETCH_APPOINTMENTS_FAILURE";
export const FETCHING_APPOINTMENTS = "FETCHING_APPOINTMENTS";

export const fetchAppointments = () => ({
  type: FETCH_APPOINTMENTS,
});
