export const FETCH_APPOINTMENTS = "FETCH_APPOINTMENTS";
export const FETCH_APPOINTMENTS_SUCCESS = "FETCH_APPOINTMENTS_SUCCESS";
export const FETCH_APPOINTMENTS_FAILURE = "FETCH_APPOINTMENTS_FAILURE";
export const FETCHING_APPOINTMENTS = "FETCHING_APPOINTMENTS";
export const FETCH_APPOINTMENT = "FETCH_APPOINTMENT";
export const FETCH_APPOINTMENT_SUCCESS = "FETCH_APPOINTMENT_SUCCESS";
export const FETCH_APPOINTMENT_FAILURE = "FETCH_APPOINTMENT_FAILURE";

export const fetchAppointments = () => ({
  type: FETCH_APPOINTMENTS,
});

export const fetchAppointment = (payload) => ({
  type: FETCH_APPOINTMENT,
  payload,
});
