export const FETCH_CONSULTATIONS = "FETCH_CONSULTATIONS";
export const FETCH_CONSULTATIONS_SUCCESS = "FETCH_CONSULTATIONS_SUCCESS";
export const FETCH_CONSULTATIONS_FAILURE = "FETCH_CONSULTATIONS_FAILURE";
export const FETCHING_CONSULTATIONS = "FETCHING_CONSULTATIONS";
export const FETCH_CONSULTATION = "FETCH_CONSULTATION";
export const FETCH_CONSULTATION_SUCCESS = "FETCH_CONSULTATION_SUCCESS";
export const FETCH_CONSULTATION_FAILURE = "FETCH_CONSULTATION_FAILURE";
export const CREATE_EVALUATION = "CREATE_EVALUATION";
export const CREATE_EVALUATION_SUCCESS = "CREATE_EVALUATION_SUCCESS";
export const CREATE_EVALUATION_FAILURE = "CREATE_EVALUATION_FAILURE";
export const CREATING_EVALUATION = "CREATING_EVALUATION";
export const CREATE_DIAGNOSIS = "CREATE_DIAGNOSIS";
export const CREATING_DIAGNOSIS = "CREATING_DIAGNOSIS";
export const CREATE_DIAGNOSIS_SUCCESS = "CREATE_DIAGNOSIS_SUCCESS";
export const CREATE_DIAGNOSIS_FAILURE = "CREATE_DIAGNOSIS_FAILURE";
export const CREATE_PRESCRIPTION = "CREATE_PRESCRIPTION";
export const CREATING_PRESCRIPTION = "CREATING_PRESCRIPTION";
export const CREATE_PRESCRIPTION_SUCCESS = "CREATE_PRESCRIPTION_SUCCESS";
export const CREATE_PRESCRIPTION_FAILURE = "CREATE_PRESCRIPTION_FAILURE";
export const CREATE_RECOMMENDATION = "CREATE_RECOMMENDATION";
export const CREATING_RECOMMENDATION = "CREATING_RECOMMENDATION";
export const CREATE_RECOMMENDATION_SUCCESS = "CREATE_RECOMMENDATION_SUCCESS";
export const CREATE_RECOMMENDATION_FAILURE = "CREATE_RECOMMENDATION_FAILURE";

export const fetchConsultations = () => ({
  type: FETCH_CONSULTATIONS,
});

export const fetchConsultation = (payload) => ({
  type: FETCH_CONSULTATION,
  payload,
});

export const createEvaluation = (payload) => ({
  type: CREATE_EVALUATION,
  payload,
});

export const createDiagnosis = (payload) => ({
  type: CREATE_DIAGNOSIS,
  payload,
});

export const createPrescription = (payload) => ({
  type: CREATE_PRESCRIPTION,
  payload,
});

export const createRecommendation = (payload) => ({
  type: CREATE_RECOMMENDATION,
  payload,
});
