export const FETCH_CONSULTATIONS = "FETCH_CONSULTATIONS";
export const FETCH_CONSULTATIONS_SUCCESS = "FETCH_CONSULTATIONS_SUCCESS";
export const FETCH_CONSULTATIONS_FAILURE = "FETCH_CONSULTATIONS_FAILURE";
export const FETCHING_CONSULTATIONS = "FETCHING_CONSULTATIONS";
export const FETCH_CONSULTATION = "FETCH_CONSULTATION";
export const FETCH_CONSULTATION_SUCCESS = "FETCH_CONSULTATION_SUCCESS";
export const FETCH_CONSULTATION_FAILURE = "FETCH_CONSULTATION_FAILURE";
export const fetchConsultations = () => ({
  type: FETCH_CONSULTATIONS,
});

export const fetchConsultation = (payload) => ({
  type: FETCH_CONSULTATION,
  payload,
});
