export const FETCH_PRESCRIPTIONS = "FETCH_PRESCRIPTIONS";
export const FETCH_PRESCRIPTIONS_SUCCESS = "FETCH_PRESCRIPTIONS_SUCCESS";
export const FETCH_PRESCRIPTIONS_FAILURE = "FETCH_PRESCRIPTIONS_FAILURE";
export const BAN_PRESCRIPTION = "BAN_PRESCRIPTION";
export const BAN_PRESCRIPTION_SUCCESS = "BAN_PRESCRIPTION_SUCCESS";
export const FETCHING_PRESCRIPTIONS = "FETCHING_PRESCRIPTIONS";

export const fetchPrescriptions = () => ({
  type: FETCH_PRESCRIPTIONS,
});

export const toggleBan = (id) => ({
  type: BAN_PRESCRIPTION,
  payload: id,
});
